# Generated by Django 5.2.13 on 2026-06-17 03:54

from django.db import migrations, models


def backfill_order_subtotals(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(subtotal=0).update(subtotal=models.F("total_price"))


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], default='percent', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(backfill_order_subtotals, migrations.RunPython.noop),
    ]
