# Generated by Django 5.2.15 on 2026-06-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_transfer_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carrier_order_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carrier_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_weight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ward_code',
        ),
    ]
